In [4]:
from tweepy import Stream
from tweepy import OAuthHandler
from tweepy.streaming import StreamListener
import json
import pandas as pd
import csv
import re #regular expression
from textblob import TextBlob
import string
import preprocessor as p

In [ ]:
#Twitter credentials for the app
consumer_key = 'xxxxx'
consumer_secret = 'xxxx'
access_key= 'xxxx'
access_secret = 'xxxx'

In [ ]:
#pass twitter credentials to tweepy
auth = tweepy.OAuthHandler(consumer_key, consumer_secret)
auth.set_access_token(access_key, access_secret)
api = tweepy.API(auth)

In [5]:
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
matrix[0:, :2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [16]:
import numpy as np
with open('/usr/share/dict/words') as f:
    words = f.read().split('\n')

def extract_word(words):
    wordlist = [w for w in words if len(w) == 5]
    return wordlist
extract_word(words)

#wordlist = np.array(wordlist)
vfunc = np.vectorize(extract_word)
print(wordlist)

mylen = np.vectorize(len)
mylen(words)
#wordlist = np.extract(len(wordlist) == 5, wordlist)
# wordlist

[]
[ 1  1  2 ...  7 10  0]
